on:
  push:
    branches:
      - main
    paths-ignore:
      - ".git/**"

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: "u2026-aweljgaf0wvn"
          server: "ssh.alecp8.sg-host.com"
          port: 18765
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "/src"
          remote_path: "/home/customer/www/alecp8.sg-host.com/public_html"
          args: "-o ConnectTimeout=5"
